unit: Applications and implications
unit_id: applications_and_implications
version: 2018
tasks:
- name: Applications and implications
  description: |
    Propose a final project that integrates the range of units covered.  
    > Think of your project plan as an ‘installation and implementation guide’ for the future. How will others be able to make your project by reading your documentation?
  outcomes:
  - Define the scope of a project
  - Develop a project plan
  checklist:
  - what will it do?
  - who has done what beforehand?
  - what materials and components will be required?
  - where will they come from?
  - how much will it cost?
  - what parts and systems will be made?
  - what processes will be used?
  - what tasks need to be completed?
  - what questions need to be answered?
  - what is the schedule?
  - how will it be evaluated?
faq: |
  No FAQ available yet
