unit: Applications and implications
unit_id: applications_and_implications
version: 2018
tasks:
- name: Applications and implications
  description: |
    Propose a final project masterpiece that integrates the range of units covered, answering the questions below.
    > See the Final Project Requirements page for a complete list of requirements you must fulfil.  
  outcomes:
  - Define the scope of a project
  - Develop a project plan
  checklist:
  - what will it do?
  - who has done what beforehand?
  - what materials and components will be required?
  - where will they come from?
  - how much will it cost?
  - what parts and systems will be made?
  - what processes will be used?
  - what tasks need to be completed?
  - what is the schedule?
  - how will it be evaluated?
  - what other questions need to be asked and answered?
faq: |
  ### Do I have to answer these questions and why?
  > Answer:
  1. These are questions to help you *plan your final project*. Answer these and any other questions you think will help you do this. 

